---
groups:
  - name: bosh-oracle-cpi-release
    jobs:
      - build-cpi
      - build-dev-cpi-release
      - build-final-cpi-release

jobs:
  - name: build-cpi
    plan:
      - {trigger: true, get: cpi-src, resource: bosh-cpi-src}

      - task: unit-tests
        file: cpi-src/ci/tasks/unit-tests.yml

  - name: build-dev-cpi-release
    serial: true
    plan:
      - aggregate:
        - {trigger: true, passed: [build-cpi], get: cpi-src, resource: bosh-cpi-src}
        - {trigger: true, get: cpi-release, resource: bosh-cpi-release-src}
        - {trigger: false, get: dev-version-semver,   params: {bump: patch}}

      - put: dev-version-semver
        params: {file: dev-version-semver/version}

      - task: build-dev-release-tarball
        file: cpi-release/ci/tasks/build-dev-release.yml

      - put: dev-release-bucket
        params:
          file: artifacts/dev_release/bosh-oracle-cpi-dev-*.tgz

  - name: build-final-cpi-release
    serial: true
    plan:
      - aggregate:
         - {trigger: false, get: final-version-semver,   params: {bump: major}}
         - {trigger: true, passed: [build-dev-cpi-release], get: cpi-release, resource: bosh-cpi-release-src}

      - task: build-final-release-tarball
        file: cpi-release/ci/tasks/build-final-release.yml

      - put: final-version-semver
        params: {file: final-version-semver/version}

      - put: final-release-bucket
        params:
          file: artifacts/release/bosh-oracle-cpi-*.tgz

resources:
  - name: bosh-cpi-release-src
    type: git
    source:
      uri: https://github.com/oracle/bosh-oracle-cpi-release.git
      branch: ((cpi-release-branch)) 
      username: ((github-user))
      password: ((github-password))

  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/oracle/bosh-oracle-cpi.git
      branch: master 
      username: ((github-user))
      password: ((github-password))

  - name: dev-release-bucket
    type: s3
    source:
       endpoint: https://((namespace)).compat.objectstorage.((region)).oraclecloud.com
       region_name: ((region))
       bucket: ((cpi-dev-release-bucket))
       regexp: bosh-oracle-cpi-(.*).tgz
       access_key_id: ((s3-access-key-id))
       secret_access_key: ((s3-secret-access-key))
       private: true

  - name: final-release-bucket
    type: s3
    source:
       endpoint: https://((namespace)).compat.objectstorage.((region)).oraclecloud.com
       region_name: ((region))
       bucket: ((cpi-final-release-bucket))
       regexp: bosh-oracle-cpi-(.*).tgz
       access_key_id: ((s3-access-key-id))
       secret_access_key: ((s3-secret-access-key))
       private: true

  - name: dev-version-semver
    type: semver
    source:
      key: current-dev-version
      bucket: ((version_semver_bucket_name))
      access_key_id: ((s3-access-key-id))
      secret_access_key: ((s3-secret-access-key))
      region_name: ((region))
      endpoint: https://((namespace)).compat.objectstorage.((region)).oraclecloud.com
      initial_version:   0.0.36

  - name: final-version-semver
    type: semver
    source:
      key: current-final-version
      bucket: ((version_semver_bucket_name))
      access_key_id: ((s3-access-key-id))
      secret_access_key: ((s3-secret-access-key))
      region_name: ((region))
      endpoint: https://((namespace)).compat.objectstorage.((region)).oraclecloud.com
      initial_version: 1.0.0