---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((docker-repo-name))/cpi-release-build-env
    tag: "latest"
inputs:
  - name: cpi-release
  - name: dev-version-semver
outputs:
  - name: artifacts
run:
  path: cpi-release/ci/tasks/build-dev-release.sh
