---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.8.3"
inputs:
  - name: cpi-release-src
  - name: oci-config
run:
  path: cpi-release-src/ci/tasks/oci-tests.sh
